/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Api Health */
        get: operations["api_health_api_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Capabilities */
        get: operations["capabilities_api_v1_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Job */
        post: operations["create_job_api_v1_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/source": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Upload Source */
        put: operations["upload_source_api_v1_jobs__job_id__source_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_v1_jobs__job_id__get"];
        put?: never;
        post?: never;
        /** Delete Job */
        delete: operations["delete_job_api_v1_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Workflow */
        put: operations["set_workflow_api_v1_jobs__job_id__workflow_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/mapping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Mapping */
        put: operations["set_mapping_api_v1_jobs__job_id__mapping_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/pleading-settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Pleading Settings */
        put: operations["set_pleading_settings_api_v1_jobs__job_id__pleading_settings_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/review": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark Review Ready */
        post: operations["mark_review_ready_api_v1_jobs__job_id__review_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview */
        get: operations["preview_api_v1_jobs__job_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Finalize */
        post: operations["finalize_api_v1_jobs__job_id__finalize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download */
        get: operations["download_api_v1_jobs__job_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/receipt.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Json Receipt */
        get: operations["download_json_receipt_api_v1_jobs__job_id__receipt_json_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/receipt.txt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Text Receipt */
        get: operations["download_text_receipt_api_v1_jobs__job_id__receipt_txt_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{job_id}/evidence.zip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Evidence Package */
        get: operations["download_evidence_package_api_v1_jobs__job_id__evidence_zip_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Analysis */
        Analysis: {
            /** Filename */
            filename: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Row Count
             * @default 0
             */
            row_count: number;
            /**
             * Column Count
             * @default 0
             */
            column_count: number;
            /** Headers */
            headers?: string[];
            /** @default unknown */
            platform: components["schemas"]["Platform"];
            /**
             * Platform Confidence
             * @default 0
             */
            platform_confidence: number;
            /** @default unknown */
            detected_workflow: components["schemas"]["DetectedWorkflow"];
            /** Rfp Layout */
            rfp_layout?: ("combined" | "separate") | null;
            /** Begin Bates Header */
            begin_bates_header?: string | null;
            /** End Bates Header */
            end_bates_header?: string | null;
            /** Prefixes */
            prefixes?: string[];
            /**
             * Request Count
             * @default 0
             */
            request_count: number;
            /**
             * Duplicate Ranges
             * @default 0
             */
            duplicate_ranges: number;
            /**
             * Gap Count
             * @default 0
             */
            gap_count: number;
            /** Issues */
            issues?: components["schemas"]["Issue"][];
            /** Personal Data Findings */
            personal_data_findings?: components["schemas"]["PersonalDataFinding"][];
        };
        /** Body_upload_source_api_v1_jobs__job_id__source_put */
        Body_upload_source_api_v1_jobs__job_id__source_put: {
            /** File */
            file: string;
        };
        /** Capabilities */
        Capabilities: {
            /** Max Upload Bytes */
            max_upload_bytes: number;
            /** Job Ttl Seconds */
            job_ttl_seconds: number;
            /** Max Active Jobs */
            max_active_jobs: number;
            /** Max Total Job Bytes */
            max_total_job_bytes: number;
            /**
             * Max Mapping Columns
             * @default 100
             */
            max_mapping_columns: number;
            /**
             * Max Source Fields Per Column
             * @default 100
             */
            max_source_fields_per_column: number;
            /** Supported Content Types */
            supported_content_types: string[];
            /** Features */
            features: string[];
        };
        /** @enum {string} */
        DetectedWorkflow: "rfp_ranges" | "privilege_log" | "unknown";
        /** FinalizeRequest */
        FinalizeRequest: {
            /** Output Filename */
            output_filename: string;
            /** Acknowledged Issue Codes */
            acknowledged_issue_codes?: string[];
            /** Review Token */
            review_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Issue */
        Issue: {
            /** Code */
            code: string;
            severity: components["schemas"]["IssueSeverity"];
            /** Message */
            message: string;
            /**
             * Overrideable
             * @default false
             */
            overrideable: boolean;
            /** Row */
            row?: number | null;
            /** Column */
            column?: string | null;
            /**
             * Count
             * @default 1
             */
            count: number;
        };
        /** @enum {string} */
        IssueSeverity: "warning" | "error" | "fatal";
        /** JobCreated */
        JobCreated: {
            /** Job Id */
            job_id: string;
            /** Expires At */
            expires_at: string;
        };
        /** JobProgress */
        JobProgress: {
            /**
             * Phase
             * @default Waiting for upload
             */
            phase: string;
            /**
             * Percent
             * @default 0
             */
            percent: number;
            /**
             * Bytes Processed
             * @default 0
             */
            bytes_processed: number;
            /**
             * Rows Processed
             * @default 0
             */
            rows_processed: number;
        };
        /**
         * JobStatus
         * @enum {string}
         */
        JobStatus: "awaiting_upload" | "uploading" | "analyzing" | "needs_configuration" | "preparing_review" | "ready_for_review" | "processing" | "complete" | "failed" | "expired";
        /** JobView */
        JobView: {
            /** Job Id */
            job_id: string;
            /** Created At */
            created_at: string;
            /** Expires At */
            expires_at: string;
            status: components["schemas"]["JobStatus"];
            progress: components["schemas"]["JobProgress"];
            workflow?: components["schemas"]["JobWorkflow"] | null;
            analysis?: components["schemas"]["Analysis"] | null;
            mapping?: components["schemas"]["MappingConfig"] | null;
            pleading_settings?: components["schemas"]["PleadingSettings"] | null;
            /** Output Filename */
            output_filename?: string | null;
            output_stats?: components["schemas"]["OutputStats"] | null;
            /** Error */
            error?: string | null;
            /** Error Code */
            error_code?: string | null;
            /**
             * Cancel Requested
             * @default false
             */
            cancel_requested: boolean;
            /**
             * Revision
             * @default 0
             */
            revision: number;
            /**
             * Configuration Revision
             * @default 0
             */
            configuration_revision: number;
            /** Reviewed Configuration Revision */
            reviewed_configuration_revision?: number | null;
            /** Review Token */
            review_token?: string | null;
            /** Staged Artifact Sha256 */
            staged_artifact_sha256?: string | null;
            /** Staged At */
            staged_at?: string | null;
            /** Input Sha256 */
            input_sha256?: string | null;
            /** Uploaded At */
            uploaded_at?: string | null;
            review_stats?: components["schemas"]["OutputStats"] | null;
            /** Reviewed Issue Codes */
            reviewed_issue_codes?: string[];
        };
        /** @enum {string} */
        JobWorkflow: "rfp_ranges" | "privilege_log";
        /** MappingConfig */
        MappingConfig: {
            /** Columns */
            columns: components["schemas"]["OutputColumn"][];
        };
        /** MappingTransform */
        MappingTransform: {
            /**
             * Kind
             * @default none
             * @enum {string}
             */
            kind: "none" | "shorten_bates" | "delimit" | "fill";
            /** Delimiter */
            delimiter?: ("; " | ", " | " | " | "\n") | null;
        };
        /** OutputColumn */
        OutputColumn: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Source Fields */
            source_fields: string[];
            transform?: components["schemas"]["MappingTransform"];
            /**
             * Normalize
             * @default false
             */
            normalize: boolean;
        };
        /** OutputStats */
        OutputStats: {
            /** Processing Ms */
            processing_ms: number;
            /** Input Rows */
            input_rows: number;
            /** Output Rows */
            output_rows: number;
            /** Output Columns */
            output_columns: number;
            /** Output Cells */
            output_cells: number;
            /** Output Size Bytes */
            output_size_bytes: number;
            /** Skipped Rows */
            skipped_rows: number;
            /** Formula Escapes */
            formula_escapes: number;
            /** Warnings Overridden */
            warnings_overridden: number;
        };
        /** @enum {string} */
        PersonalDataCategory: "ssn" | "date_of_birth" | "personal_email" | "single_word_name";
        /** PersonalDataFinding */
        PersonalDataFinding: {
            category: components["schemas"]["PersonalDataCategory"];
            /** Count */
            count: number;
            /** Columns */
            columns: string[];
        };
        /** @enum {string} */
        Platform: "logikcull" | "everlaw" | "unknown";
        /** PleadingSettings */
        PleadingSettings: {
            /**
             * Delimiter
             * @default comma
             * @enum {string}
             */
            delimiter: "comma" | "semicolon" | "pipe" | "newline";
            /**
             * Include And
             * @default true
             */
            include_and: boolean;
        };
        /** Preview */
        Preview: {
            /** Headers */
            headers: string[];
            /** Rows */
            rows: string[][];
            /** Total Rows */
            total_rows: number;
            /** Skipped Rows */
            skipped_rows: number;
            /** Formula Escapes */
            formula_escapes: number;
            /** Artifact Sha256 */
            artifact_sha256?: string | null;
            /**
             * Configuration Revision
             * @default 0
             */
            configuration_revision: number;
            /**
             * Sample Truncated
             * @default false
             */
            sample_truncated: boolean;
            /** Review Token */
            review_token?: string | null;
            /** Text */
            text?: string | null;
        };
        /** ReviewRequest */
        ReviewRequest: {
            /** Acknowledged Issue Codes */
            acknowledged_issue_codes?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WorkflowUpdate */
        WorkflowUpdate: {
            workflow: components["schemas"]["JobWorkflow"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                };
            };
        };
    };
    api_health_api_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: number | string;
                    };
                };
            };
        };
    };
    capabilities_api_v1_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Capabilities"];
                };
            };
        };
    };
    create_job_api_v1_jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCreated"];
                };
            };
        };
    };
    upload_source_api_v1_jobs__job_id__source_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_source_api_v1_jobs__job_id__source_put"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_v1_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_job_api_v1_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_workflow_api_v1_jobs__job_id__workflow_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkflowUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_mapping_api_v1_jobs__job_id__mapping_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MappingConfig"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_pleading_settings_api_v1_jobs__job_id__pleading_settings_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PleadingSettings"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    mark_review_ready_api_v1_jobs__job_id__review_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["ReviewRequest"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_api_v1_jobs__job_id__preview_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Preview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    finalize_api_v1_jobs__job_id__finalize_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FinalizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_api_v1_jobs__job_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_json_receipt_api_v1_jobs__job_id__receipt_json_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_text_receipt_api_v1_jobs__job_id__receipt_txt_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_evidence_package_api_v1_jobs__job_id__evidence_zip_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
